### ISSUE TITLE
No autorun mode

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rusq/disable-hdd-apm#1]
```
Quite useful application!
But it would be great to make it support autorun-mode: start minimized, working 
with specified hdd. At least with command-line switches.
```

Original issue reported on code.google.com by `Std.De...@gmail.com` on 29 Sep 2013 at 9:41

**Comment by GoogleCodeExporter** [comment]
Original comment by `gilya...@gmail.com` on 22 Dec 2014 at 11:28
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Thanks for your feedback, I'll see what I can do.
```

Original comment by `gilya...@gmail.com` on 22 Dec 2014 at 11:29

**Comment by rusq** [comment]
Probably I will never come around to this.
